COUNTABLE_FOODS = {
    "egg": 50,
    "apple": 180,
    "date": 8,
    "apricot": 35,
    "avocado": 200,
    "banana": 120,
    "strawberry": 12,
    "cherry": 8,
    "blueberry": 2,
    "raspberry": 4,
    "mango": 250,
    "peach": 150,
    "lemon": 100,
    "pear": 180,
    "fig": 50,
    "grape": 5,
    "kiwi": 75,
    "orange": 150,
}

USDA_MAPPING = {
    "cheese butter": "butter",
    "juice": "fruit juice",
    "almond": "almonds",
    "cashew": "cashews",
    "soy": "soybeans",
    "walnut": "walnuts",
    "peanut": "peanuts",
    "date": "dates",
    "strawberry": "strawberries",
    "cherry": "cherries",
    "blueberry": "blueberries",
    "raspberry": "raspberries",
    "grape": "grapes",
    "kiwi": "kiwi fruit",
    "steak": "beef steak",
    "chicken duck": "chicken meat",
    "hamburg": "hamburger",
    "hanamaki baozi": "steamed bun",
    "wonton dumplings": "wonton",
    "rice": "white rice cooked",
    "spring onion": "green onion",
    "rape": "rapeseed greens",
    "white radish": "daikon radish",
    "celery stick": "celery",
    "cilantro mint": "cilantro",
    "pepper": "bell pepper",
    "French beans": "green beans",
    "shiitake": "shiitake mushroom",
    "white button mushroom": "white mushroom",
    "other ingredients": "mixed vegetables",
    "pork": "pork loin raw",
    "bread": "white bread",
    "fish": "salmon raw",
    "chicken duck": "chicken breast raw",
    "shrimp": "shrimp raw",
    "potato": "potato raw",
    "tomato": "tomato raw",
}